name: CI

on:
  schedule:
    - cron: "0 0 28 * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Create Issue
      uses: froi/create-financials-issue@v1.0.0
      with:
        title: "Add financial data for the month"
        assignees: "jpadilla,froi" 
        labels: "community,finance"
        
      env:
       GITHUB_TOKEN : ${{secrets.GITHUB_TOKEN}}
